apiVersion: v2
name: inventory-service
description: inventory service
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"