apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: monitoring-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - default/app-gateway
  http:
  # Kiali
  - match:
    - uri:
        prefix: /api/kiali
    rewrite:
      uri: /kiali/
    route:
    - destination:
        host: kiali
        port:
          number: 20001
  
  # Jaeger
  - match:
    - uri:
        prefix: /api/jaeger
    rewrite:
      uri: /
    route:
    - destination:
        host: jaeger-query
        port:
          number: 16686