kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-lab
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Istio HTTP (NodePort 31541 -> Host 80)
  - containerPort: 31541
    hostPort: 80
    protocol: TCP
  - containerPort: 31542
    hostPort: 8081
    protocol: TCP
  - containerPort: 31543
    hostPort: 8082
    protocol: TCP
  # Monitoring Gateway (NodePort 31544 -> Host 9090)
  - containerPort: 31544
    hostPort: 9090
    protocol: TCP
  # Istio HTTPS (NodePort 31026 -> Host 443)
  - containerPort: 31026
    hostPort: 443
    protocol: TCP
  # Istio Ingress Gateway Status
  - containerPort: 15021
    hostPort: 15021
    protocol: TCP
- role: worker
  labels:
    zone: zone-a
- role: worker
  labels:
    zone: zone-b
- role: worker
  labels:
    zone: zone-c
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5002"]
        endpoint = ["http://kind-registry:5002"]