apiVersion: v2
name: user-service
description: user-service service
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"